<table>
    <thead>
        <tr>
            <th>Naziv</th>
            <th>Pregled</th>
            <th>Veterinar</th>
            <th>Datum početka</th>
            <th style="text-align: right;">
            <a href="<?=App::config('url')?>ordinacija/novo">Dodaj novu</a>
            </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($entiteti as $red): ?>
            <tr>
                <td><?=$red->naziv?></td>
                <td><?=$red->pregled?></td>
                <td><?=$red->veterinar?></td>
                <td><?=$red->datumpocetka?></td>
                <td>
                    <a href="<?=App::config('url')?>ordinacija/promjena?sifra=<?=$red->sifra?>">
                        <i title="promjena" class="fas fa-2x fa-pencil-alt"></i>
                    </a>
                    <?php if($red->radnika==0): ?>
                        <a href="<?=App::config('url')?>ordinacija/brisanje?sifra=<?=$red->sifra?>"
                        onclick="return confirm('Sigurno obrisati <?=Funkcije::escapeSingleQuote($red->naziv) ?>?');">
                        <i title="brisanje" style="color: red" class="fas fa-trash-alt"></i></a>
                    <?php endif;?>
                </td>
            </tr>

        <?php endforeach; ?>
    </tbody>
</table>