<form class="log-in-form" 
action="<?=App::config('url')?>ordinacija/novo"
    method="POST">
    <h4 class="text-center">Dodavanje nove ordinacije</h4>



  <div class="grid-x grid-padding-x">
    <div class="cell large-6">
    <label>Naziv
          <input type="text" name="naziv" value="<?=$entitet->naziv?>">
        </label>
      </div>
    <div class="cell large-6">
    <label>Pregled
        <select name="pregled">
          <?php foreach($pregledi as $pregled): ?>
            <option <?php 
              if($entitet->pregled==$pregled->sifra){
                echo ' selected="selected" ';
              }
              ?> value="<?=$pregled->sifra ?>"><?=$pregled->naziv ?></option>
          <?php endforeach; ?>
        </select>
      </label>
    </div>
  </div>

  


  <div class="grid-x grid-padding-x">
    <div class="cell large-6">
    <label>Datum početka
      <input type="datetime-local"
       name="datumpocetka" value="<?=$entitet->datumpocetka; ?>"> 
      </label>
    </div>
    <div class="cell large-6">
    
      <label>Veterinar
      <select name="veterinar">
          <?php foreach($veterinari as $veterinar): ?>
            <option <?php 
              if($entitet->veterinar==$veterinar->sifra){
                echo ' selected="selected" ';
              }
              ?> value="<?=$veterinar->sifra ?>"><?=$veterinar->ime . ' ' . $veterinar->prezime; ?></option>
          <?php endforeach; ?>
        </select>
      </label>
    </div>
  </div>
  
 
<div class="grid-x grid-padding-x">
    <div class="cell">
     <div class="callout">
      <?=$poruka?>
     </div>
    </div>
  </div>
  

<div class="grid-x grid-padding-x">
  <div class="cell small-6 medium-6 large-6">
    <a class="alert button expanded" 
    href="<?=App::config('url')?>ordinacija/index">Nazad</a>
  </div>
  <div class="cell small-6 medium-6 large-6">
    <input type="submit" class="button expanded" value="Dodaj"></input>
  </div>
</div>

</form>