<form class="log-in-form" 
    action="<?=App::config('url')?>pregled/novo"
    method="POST">
  <h4 class="text-center">Dodavanje novog pregleda</h4>
  <label>Naziv
    <input type="text" name="naziv" value="<?=$pregled->naziv?>">
  </label>

  <label>Trajanje
  <input type="number" min="1" max="320" name="trajanje" value="<?=$pregled->trajanje?>">
  </label>

  <label>Cijena
    <input type="text" name="cijena" value="<?=$pregled->cijena?>">
  </label>

  <label>Plaćanje
        <select name="placanje">
        <option 
        <?php 
        if($pregled->placanje==='1'){
            echo ' selected="selected" ';
        }
        ?>
         value="1">DA</option>


        <option 
        <?php 
        if($pregled->placanje==='0'){
            echo ' selected="selected" ';
        }
        ?>
         value="0">NE</option>
        </select>
  </label>
 
  <?=$poruka?>

<div class="grid-x grid-padding-x">
  <div class="cell medium-6 large-6">
    <a class="alert button expanded" 
        href="<?=App::config('url')?>pregled/index">Nazad</a>
  </div>
  <div class="cell medium-6 large-6">
    <input type="submit" class="button expanded" value="Dodaj"></input>
  </div>
</div>
</form>